### ISSUE TITLE
KKS POV?

### ISSUE THREAD

**Issue by novalaunchersa** [tony246642/KK_MainGameVR#2]
Do you think you can do the same with KKS_VR? since it's forked from KK_MainGameVR I guess the process would be similar https://github.com/IllusionMods/KKS_VR

**Comment by tony246642** [comment]
POV feature has been merged into [KKS_VR v1.5](https://github.com/IllusionMods/KKS_VR/releases/tag/v1.5)
Thanks for the KKS contributors
